-- Seed portfolio projects
INSERT INTO projects (title, slug, description, short_description, category_id, technologies, project_url, github_url, year, client, duration) VALUES
(
    'E-commerce Platform',
    'ecommerce-platform',
    'A comprehensive e-commerce solution built with modern technologies. Features include user authentication, product catalog, shopping cart, payment processing, order management, and admin dashboard. The platform is fully responsive and optimized for performance.',
    'Modern e-commerce solution with seamless user experience and responsive design.',
    (SELECT id FROM categories WHERE slug = 'web-design'),
    ARRAY['React', 'Next.js', 'Tailwind CSS', 'Stripe', 'PostgreSQL'],
    'https://ecommerce-demo.example.com',
    'https://github.com/username/ecommerce-platform',
    2024,
    'TechCorp Inc.',
    '3 months'
),
(
    'Task Management App',
    'task-management-app',
    'A collaborative task management application with real-time updates, team features, project organization, and deadline tracking. Built with modern web technologies and featuring a clean, intuitive interface.',
    'Collaborative task management tool with real-time updates and team features.',
    (SELECT id FROM categories WHERE slug = 'development'),
    ARRAY['TypeScript', 'Node.js', 'MongoDB', 'Socket.io', 'React'],
    'https://taskapp-demo.example.com',
    'https://github.com/username/task-management',
    2024,
    'StartupXYZ',
    '4 months'
),
(
    'Brand Identity System',
    'brand-identity-system',
    'Complete brand identity design including logo creation, color palette, typography selection, brand guidelines, business card design, and marketing materials. The project involved extensive research and multiple design iterations.',
    'Complete brand identity including logo, colors, typography, and guidelines.',
    (SELECT id FROM categories WHERE slug = 'branding'),
    ARRAY['Figma', 'Adobe Illustrator', 'Adobe Photoshop', 'InDesign'],
    NULL,
    NULL,
    2023,
    'Creative Agency Co.',
    '6 weeks'
),
(
    'Creative Agency Website',
    'creative-agency-site',
    'Award-winning website design for a creative agency featuring stunning animations, smooth transitions, and an immersive user experience. The site showcases the agency''s portfolio and services with a focus on visual storytelling.',
    'Award-winning website design for a creative agency with stunning animations.',
    (SELECT id FROM categories WHERE slug = 'web-design'),
    ARRAY['Vue.js', 'GSAP', 'CSS3', 'Webpack', 'Netlify'],
    'https://creative-agency.example.com',
    'https://github.com/username/creative-agency',
    2023,
    'Creative Minds Agency',
    '8 weeks'
),
(
    'Analytics Dashboard',
    'analytics-dashboard',
    'Data visualization dashboard with interactive charts, real-time metrics, and comprehensive reporting features. The dashboard provides insights into user behavior, sales performance, and business KPIs with customizable widgets.',
    'Data visualization dashboard with interactive charts and real-time metrics.',
    (SELECT id FROM categories WHERE slug = 'development'),
    ARRAY['React', 'D3.js', 'Python', 'FastAPI', 'PostgreSQL'],
    'https://analytics-demo.example.com',
    'https://github.com/username/analytics-dashboard',
    2023,
    'DataTech Solutions',
    '5 months'
),
(
    'Mobile Banking App',
    'mobile-banking-app',
    'Secure mobile banking application with biometric authentication, transaction history, bill payments, and account management. The app features a modern UI/UX design with emphasis on security and user experience.',
    'Secure mobile banking app with biometric authentication and modern UI.',
    (SELECT id FROM categories WHERE slug = 'mobile'),
    ARRAY['React Native', 'TypeScript', 'Redux', 'Firebase'],
    NULL,
    NULL,
    2023,
    'SecureBank',
    '6 months'
);
